version: '2.1'

services:
  customer:
    build: customer-service
    mem_limit: 350m
    ports:
      - "9000"
    depends_on:
      - db-customer  
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-customer:5432/customer
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  order:
    build: order-service
    mem_limit: 350m
    ports:
      - "8000"
    depends_on:
      - db-order
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-order:5432/order
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  eureka:
    build: eureka-server
    mem_limit: 350m
    ports:
      - "8761:8761"    
  db-customer:
    image: 'postgres:13.1-alpine'
    container_name: db-customer
    environment:
      - POSTGRES_DB=customer
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
  db-order:
    image: 'postgres:13.1-alpine'
    container_name: db-order
    environment:
      - POSTGRES_DB=order
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123       