server:
  port: 9000
spring:
  profiles: docker
  datasource:
    url: jdbc:h2:mem:customer
    driverClassName: org.h2.Driver
    username: admin
    password: 1233
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  h2:
    console:
      enabled: true
        